ingress:
  enabled: true
  name: my-ingress
  namespace: default  
  ingressClassName: nginx
  tls: []
  hosts: 
    - host: another.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: my-service
            port: 80