ingress:
  enabled: true
  name: my-ingress
  namespace: default   
  tls: []
  hosts: 
    - host: another.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: another-service
            port: 80