# This is a basic workflow to help you get started with Actions

name: Package and Publish Helm Chart

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
    branches:
      - main   
    paths:
       - 'charts/**'
       - '.github/workflows/publish-helm.yaml'
   pull_request:
    branches:
      - main 
    paths:
       - 'charts/**'
       - '.github/workflows/publish-helm.yml'
   workflow_dispatch:
permissions:
  contents: write  # Required for pushing to gh-pages
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  package:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
    
    - name: Package the Helm chart
      run: |
        helm package charts -d repo/charts  
        helm repo index repo/charts --url https://LeilaZarban.github.io/webapi-helm-charts  
    - name: Upload charts to Azure Blob Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_KEY }} --destination ${{ secrets.AZURE_CONTAINER_NAME }} --source repo --overwrite

    